from decouple import config

SCHEMAS_PATH = config("SCHEMAS_PATH")
CATALOGUE_SCHEME = config("CATALOGUE_SCHEME")
CATALOGUE_HOST = config("CATALOGUE_HOST")
CATALOGUE_PORT = config("CATALOGUE_PORT")
CATALOGUE_DEBUG = config("CATALOGUE_DEBUG")
